-- Phase 3: household creation, invitation mechanism and max-2 limit.
-- Adds: invitations table, join_code on households, RPC functions,
-- household member limit trigger and related RLS policies.

-- ============================================================
-- 1. Join code for households (used for invitation links)
-- ============================================================
alter table public.households
  add column join_code text not null default
    upper(encode(extensions.gen_random_bytes(4), 'hex'));

create unique index households_join_code_unique on public.households (join_code);

comment on column public.households.join_code is
  'Short uppercase code for household invitations (e.g. A1B2C3D4).';

-- ============================================================
-- 2. Invitations table
-- ============================================================
create table public.invitations (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households (id) on delete cascade,
  token text not null default encode(extensions.gen_random_bytes(16), 'hex'),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '7 days'),
  used_by uuid references public.profiles (id) on delete set null,
  used_at timestamptz
);

comment on table public.invitations is
  'Invitation tokens for joining a household (one-time use).';

-- Index for fast token lookups during accept
create index invitations_token_unique on public.invitations (token) where used_by is null;

-- ============================================================
-- 3. Max-2 household limit trigger
-- ============================================================
create or replace function private.profile_household_limit()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare
  current_member_count int;
begin
  if new.household_id is distinct from old.household_id and new.household_id is not null then
    -- Advisory lock prevents two concurrent transactions from both seeing count=1
    perform pg_advisory_xact_lock(hashtext('household_members:' || new.household_id));

    select count(*) into current_member_count
    from public.profiles
    where household_id = new.household_id;

    if current_member_count >= 2 then
      raise exception 'Household is full. A household can only have 2 members.'
        using errcode = 'check_violation';
    end if;
  end if;

  return new;
end;
$$;

comment on function private.profile_household_limit() is
  'Enforces max 2 members per household on profile insert/update. Uses advisory lock to prevent race conditions.';

create trigger profiles_household_limit
  before insert or update of household_id on public.profiles
  for each row execute procedure private.profile_household_limit();

-- ============================================================
-- 4. RPC: create_household
-- ============================================================
create or replace function public.create_household(household_name text)
returns public.households
language plpgsql
security definer set search_path = ''
as $$
declare
  new_household public.households%rowtype;
  caller_id uuid;
begin
  caller_id := auth.uid();

  if caller_id is null then
    raise exception 'Not authenticated';
  end if;

  -- Caller must not already belong to a household
  if exists (
    select 1 from public.profiles
    where id = caller_id and household_id is not null
  ) then
    raise exception 'You already belong to a household. Leave it before creating a new one.'
      using errcode = 'check_violation';
  end if;

  -- Validate household name
  if length(btrim(household_name)) = 0 then
    raise exception 'Household name cannot be empty.'
      using errcode = 'check_violation';
  end if;

  -- Create household (join_code is generated by column default)
  insert into public.households (name) values (household_name)
  returning * into new_household;

  -- Link the caller to this household
  update public.profiles
  set household_id = new_household.id
  where id = caller_id;

  return new_household;
end;
$$;

comment on function public.create_household(text) is
  'Creates a new household and links the authenticated caller to it. Caller must not already belong to a household.';

-- ============================================================
-- 5. RPC: generate_invitation_code
-- ============================================================
create or replace function public.generate_invitation_code()
returns public.invitations
language plpgsql
security definer set search_path = ''
as $$
declare
  caller_household uuid;
  new_invitation public.invitations%rowtype;
begin
  caller_household := private.my_household_id();

  if caller_household is null then
    raise exception 'You must belong to a household before generating invitations.';
  end if;

  -- Prevent duplicates: only one active invitation per household at a time
  delete from public.invitations
  where household_id = caller_household and used_by is null;

  insert into public.invitations (household_id)
  values (caller_household)
  returning * into new_invitation;

  return new_invitation;
end;
$$;

comment on function public.generate_invitation_code() is
  'Generates a fresh invitation token for the caller household. Invalidates any previous unused tokens.';

-- ============================================================
-- 6. RPC: accept_invitation_code
-- ============================================================
create or replace function public.accept_invitation_code(invite_code text)
returns public.households
language plpgsql
security definer set search_path = ''
as $$
declare
  invitation_record record;
  caller_id uuid;
  joined_household public.households%rowtype;
begin
  caller_id := auth.uid();

  if caller_id is null then
    raise exception 'Not authenticated';
  end if;

  -- Validate the invitation (may be expired or already used)
  select * into invitation_record
  from public.invitations
  where token = invite_code;

  if invitation_record is null then
    raise exception 'Invalid invitation code. Please check and try again.'
      using errcode = 'check_violation';
  end if;

  if invitation_record.used_by is not null then
    raise exception 'This invitation has already been used.'
      using errcode = 'check_violation';
  end if;

  if invitation_record.expires_at < now() then
    raise exception 'This invitation has expired. Ask for a new one.'
      using errcode = 'check_violation';
  end if;

  -- Caller must not already belong to a household
  if exists (
    select 1 from public.profiles
    where id = caller_id and household_id is not null
  ) then
    raise exception 'You already belong to a household. Leave it before joining a new one.'
      using errcode = 'check_violation';
  end if;

  -- The limit trigger will raise if household is full (2 members)

  -- Join the household
  update public.profiles
  set household_id = invitation_record.household_id
  where id = caller_id;

  -- Mark invitation as used
  update public.invitations
  set used_by = caller_id, used_at = now()
  where id = invitation_record.id;

  select * into joined_household
  from public.households
  where id = invitation_record.household_id;

  return joined_household;
end;
$$;

comment on function public.accept_invitation_code(text) is
  'Accepts an invitation token, links the caller to the household. Enforces: one active invitation, max-2 members, no double-join.';

-- ============================================================
-- 7. Grants
-- ============================================================
-- Revoke default access to new objects from anon
revoke all on table public.invitations from anon, authenticated;

-- Allow authenticated to SELECT invitations (for household members reading their own)
grant select on table public.invitations to authenticated;

-- RPCs are callable by authenticated
grant execute on function public.create_household(text) to authenticated;
grant execute on function public.generate_invitation_code() to authenticated;
grant execute on function public.accept_invitation_code(text) to authenticated;

-- ============================================================
-- 8. RLS policies on invitations
-- ============================================================
alter table public.invitations enable row level security;

-- Members can see invitations for their own household
create policy "invitations_select_own_household"
  on public.invitations for select
  to authenticated
  using (household_id = (select private.my_household_id()));